title: "Dejanir Junior"
description: "Technology Strategy | Project Leadership | Education Systems"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Dejanir Junior"
  bio: "Technology Strategy | Project Leadership | Education Systems"
  location: "Brazil"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/juniordejanir"
    - label: "GitHub"
      url: "https://github.com/dejanirjunior"
